/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package My_Form;

import javax.swing.JOptionPane;
import java.sql.*;
import My_Classes.DB_connect;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import javax.swing.JComboBox;

/**
 *
 * @author Administrator
 */
public class BookReports extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BookReports.class.getName());

    /**
     * Creates new form NewJFrame
     */
    private boolean isLoading = false;
    private String currentView = "inventory";

    public BookReports() {
        setUndecorated(true); // REQUIRED for opacity
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        tblModel.getTableHeader().setPreferredSize(
                new java.awt.Dimension(tblModel.getTableHeader().getWidth(), 50)
        );
        tblModel.getTableHeader().setFont(
                tblModel.getTableHeader().getFont().deriveFont(24f)
        );

        tblModel.setFont(tblModel.getFont().deriveFont(18f));
        tblModel.setFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 24));

        // 2. Increase the row height so the large text isn't cut off
        tblModel.setRowHeight(35);

        loadCategories(cmbCategory);
        loadCategories(cmbCategory);

// trigger after UI is ready
        if (cmbCategory.getItemCount() > 0) {
            cmbCategory.setSelectedIndex(0);
        }
    }

    public void loadCategories(JComboBox<String> cmbCategory) {
        isLoading = true; // stop event firing

        try {
            Connection con = DB_connect.getConnection();
            String sql = "SELECT category_name FROM category";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            cmbCategory.removeAllItems();

            cmbCategory.addItem("All");

            while (rs.next()) {
                cmbCategory.addItem(rs.getString("category_name"));
            }

            // ensure selection
            if (cmbCategory.getItemCount() > 0) {
                cmbCategory.setSelectedIndex(0);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        isLoading = false; // allow events again
    }

    public void loadTableData(String sql, Object... params) {

        try {
            Connection con = DB_connect.getConnection();
            PreparedStatement pst = con.prepareStatement(sql);

            for (int i = 0; i < params.length; i++) {
                pst.setObject(i + 1, params[i]);
            }

            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tblModel.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("book_id"),
                    rs.getString("title"),
                    rs.getString("author"),
                    rs.getString("category_name"),
                    rs.getInt("total_copies"),
                    rs.getInt("available_copies"),
                    rs.getInt("borrowed_count"),
                    rs.getString("status")
                });
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading data: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMembers = new javax.swing.JLabel();
        txtTransactions = new javax.swing.JLabel();
        txtReports = new javax.swing.JLabel();
        txtLogout1 = new javax.swing.JLabel();
        txtDashboard = new javax.swing.JLabel();
        txtBooks = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblModel = new javax.swing.JTable();
        btnExport = new javax.swing.JButton();
        btnRecentlyAdded = new javax.swing.JButton();
        btnNeverBorrowed = new javax.swing.JButton();
        btnMostPopular = new javax.swing.JButton();
        cmbCategory = new javax.swing.JComboBox<>();
        btnInventorySummary = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Library Inventory System");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/My_Image/Adobe_Express_-_file-removebg-preview.png"))); // NOI18N

        txtMembers.setBackground(new java.awt.Color(204, 204, 204));
        txtMembers.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtMembers.setText("Members");
        txtMembers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMembersMouseClicked(evt);
            }
        });

        txtTransactions.setBackground(new java.awt.Color(204, 204, 204));
        txtTransactions.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtTransactions.setText("Transactions");
        txtTransactions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTransactionsMouseClicked(evt);
            }
        });

        txtReports.setBackground(new java.awt.Color(204, 204, 204));
        txtReports.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtReports.setText("Reports");
        txtReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtReportsMouseClicked(evt);
            }
        });

        txtLogout1.setBackground(new java.awt.Color(204, 204, 204));
        txtLogout1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtLogout1.setText("Logout");
        txtLogout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLogout1MouseClicked(evt);
            }
        });

        txtDashboard.setBackground(new java.awt.Color(255, 255, 255));
        txtDashboard.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtDashboard.setText("Dashboard");
        txtDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDashboardMouseClicked(evt);
            }
        });

        txtBooks.setBackground(new java.awt.Color(204, 204, 204));
        txtBooks.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtBooks.setText("Books");
        txtBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBooksMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(120, 120, 120)
                .addComponent(txtDashboard)
                .addGap(30, 30, 30)
                .addComponent(txtBooks)
                .addGap(30, 30, 30)
                .addComponent(txtMembers)
                .addGap(30, 30, 30)
                .addComponent(txtTransactions)
                .addGap(30, 30, 30)
                .addComponent(txtReports)
                .addGap(30, 30, 30)
                .addComponent(txtLogout1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtBooks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtMembers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTransactions)
                                .addComponent(txtReports)
                                .addComponent(txtLogout1))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2189, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Category:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 140, 34));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel9.setText("Book Reports");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, -1, -1));

        tblModel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        tblModel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Title", "Author", "Category", "Total Copies", "Available", "Borrowed", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblModel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 1440, 600));

        btnExport.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExport.setText("Export");
        btnExport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExportMouseClicked(evt);
            }
        });
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });
        getContentPane().add(btnExport, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 340, 100, 44));

        btnRecentlyAdded.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRecentlyAdded.setText("Recently Added");
        btnRecentlyAdded.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecentlyAddedActionPerformed(evt);
            }
        });
        getContentPane().add(btnRecentlyAdded, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 240, 200, 44));

        btnNeverBorrowed.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNeverBorrowed.setText("Never Borrowed");
        btnNeverBorrowed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNeverBorrowedActionPerformed(evt);
            }
        });
        getContentPane().add(btnNeverBorrowed, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 200, 44));

        btnMostPopular.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMostPopular.setText("Most Popular");
        btnMostPopular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostPopularActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostPopular, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, 200, 44));

        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Student", "Teacher", "Guest" }));
        cmbCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoryActionPerformed(evt);
            }
        });
        getContentPane().add(cmbCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 160, 40));

        btnInventorySummary.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnInventorySummary.setText("Inventory Summary");
        btnInventorySummary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInventorySummaryMouseClicked(evt);
            }
        });
        btnInventorySummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventorySummaryActionPerformed(evt);
            }
        });
        getContentPane().add(btnInventorySummary, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 220, 44));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMembersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMembersMouseClicked
        BookReports member = new BookReports();
        member.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtMembersMouseClicked

    private void txtTransactionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTransactionsMouseClicked
        Transactions transaction = new Transactions();
        transaction.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtTransactionsMouseClicked

    private void txtReportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtReportsMouseClicked
        Reports report = new Reports();
        report.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtReportsMouseClicked

    private void txtLogout1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLogout1MouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        LoginForm login = new LoginForm();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtLogout1MouseClicked

    private void txtDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDashboardMouseClicked
        Dashboard dashboard = new Dashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtDashboardMouseClicked

    private void txtBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBooksMouseClicked
        Books book = new Books(); // create instance
        book.setVisible(true); // show it
        this.dispose();
    }//GEN-LAST:event_txtBooksMouseClicked

    private void btnExportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExportMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportMouseClicked

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // TODO add your handling code here:

        // Set filename based on current view
        String defaultFileName;
        String sheetName;
        String reportTitle;
        String category = cmbCategory.getSelectedItem() != null ? cmbCategory.getSelectedItem().toString() : "All";

        switch (currentView) {
            case "popular":
                defaultFileName = "BookReport_MostPopular.xlsx";
                sheetName = "Most Popular";
                reportTitle = "Most Popular Books - " + category;
                break;
            case "never":
                defaultFileName = "BookReport_NeverBorrowed.xlsx";
                sheetName = "Never Borrowed";
                reportTitle = "Never Borrowed Books - " + category;
                break;
            case "recent":
                defaultFileName = "BookReport_RecentlyAdded.xlsx";
                sheetName = "Recently Added";
                reportTitle = "Recently Added Books - " + category;
                break;
            default:
                defaultFileName = "BookReport_Inventory.xlsx";
                sheetName = "Inventory Summary";
                reportTitle = "Inventory Summary - " + category;
                break;
        }

        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setDialogTitle("Save Excel File");
        fileChooser.setSelectedFile(new java.io.File(defaultFileName));
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Excel Files", "xlsx"));

        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection != javax.swing.JFileChooser.APPROVE_OPTION) {
            return;
        }

        java.io.File fileToSave = fileChooser.getSelectedFile();
        if (!fileToSave.getName().endsWith(".xlsx")) {
            fileToSave = new java.io.File(fileToSave.getAbsolutePath() + ".xlsx");
        }

        try (org.apache.poi.xssf.usermodel.XSSFWorkbook workbook = new org.apache.poi.xssf.usermodel.XSSFWorkbook()) {

            org.apache.poi.xssf.usermodel.XSSFSheet sheet = workbook.createSheet(sheetName);
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblModel.getModel();

            // ── Title style ──────────────────────────────────────────
            org.apache.poi.xssf.usermodel.XSSFCellStyle titleStyle = workbook.createCellStyle();
            org.apache.poi.xssf.usermodel.XSSFFont titleFont = workbook.createFont();
            titleFont.setBold(true);
            titleFont.setFontHeightInPoints((short) 16);
            titleStyle.setFont(titleFont);
            titleStyle.setFillForegroundColor(new org.apache.poi.xssf.usermodel.XSSFColor(
                    new byte[]{(byte) 204, (byte) 204, (byte) 255}, null));
            titleStyle.setFillPattern(org.apache.poi.ss.usermodel.FillPatternType.SOLID_FOREGROUND);

            // Write title row (row 0)
            org.apache.poi.ss.usermodel.Row titleRow = sheet.createRow(0);
            titleRow.setHeightInPoints(30);
            org.apache.poi.ss.usermodel.Cell titleCell = titleRow.createCell(0);
            titleCell.setCellValue(reportTitle);
            titleCell.setCellStyle(titleStyle);
            // Merge title across all columns
            sheet.addMergedRegion(new org.apache.poi.ss.util.CellRangeAddress(0, 0, 0, model.getColumnCount() - 1));

            // ── Header style ─────────────────────────────────────────
            org.apache.poi.xssf.usermodel.XSSFCellStyle headerStyle = workbook.createCellStyle();
            org.apache.poi.xssf.usermodel.XSSFFont headerFont = workbook.createFont();
            headerFont.setBold(true);
            headerFont.setFontHeightInPoints((short) 12);
            headerStyle.setFont(headerFont);
            headerStyle.setFillForegroundColor(new org.apache.poi.xssf.usermodel.XSSFColor(
                    new byte[]{(byte) 100, (byte) 100, (byte) 200}, null));
            headerStyle.setFillPattern(org.apache.poi.ss.usermodel.FillPatternType.SOLID_FOREGROUND);
            headerStyle.setBorderBottom(org.apache.poi.ss.usermodel.BorderStyle.THIN);
            headerStyle.setBorderTop(org.apache.poi.ss.usermodel.BorderStyle.THIN);
            headerStyle.setBorderLeft(org.apache.poi.ss.usermodel.BorderStyle.THIN);
            headerStyle.setBorderRight(org.apache.poi.ss.usermodel.BorderStyle.THIN);
            // White bold font for header
            org.apache.poi.xssf.usermodel.XSSFFont headerFontWhite = workbook.createFont();
            headerFontWhite.setBold(true);
            headerFontWhite.setFontHeightInPoints((short) 12);
            headerFontWhite.setColor(org.apache.poi.ss.usermodel.IndexedColors.WHITE.getIndex());
            headerStyle.setFont(headerFontWhite);

            // Write header row (row 1)
            org.apache.poi.ss.usermodel.Row headerRow = sheet.createRow(1);
            for (int col = 0; col < model.getColumnCount(); col++) {
                org.apache.poi.ss.usermodel.Cell cell = headerRow.createCell(col);
                cell.setCellValue(model.getColumnName(col));
                cell.setCellStyle(headerStyle);
            }

            // ── Data styles (alternating rows) ───────────────────────
            org.apache.poi.xssf.usermodel.XSSFCellStyle dataStyleLight = workbook.createCellStyle();
            dataStyleLight.setBorderBottom(org.apache.poi.ss.usermodel.BorderStyle.THIN);
            dataStyleLight.setBorderTop(org.apache.poi.ss.usermodel.BorderStyle.THIN);
            dataStyleLight.setBorderLeft(org.apache.poi.ss.usermodel.BorderStyle.THIN);
            dataStyleLight.setBorderRight(org.apache.poi.ss.usermodel.BorderStyle.THIN);

            org.apache.poi.xssf.usermodel.XSSFCellStyle dataStyleDark = workbook.createCellStyle();
            dataStyleDark.setFillForegroundColor(new org.apache.poi.xssf.usermodel.XSSFColor(
                    new byte[]{(byte) 235, (byte) 235, (byte) 255}, null));
            dataStyleDark.setFillPattern(org.apache.poi.ss.usermodel.FillPatternType.SOLID_FOREGROUND);
            dataStyleDark.setBorderBottom(org.apache.poi.ss.usermodel.BorderStyle.THIN);
            dataStyleDark.setBorderTop(org.apache.poi.ss.usermodel.BorderStyle.THIN);
            dataStyleDark.setBorderLeft(org.apache.poi.ss.usermodel.BorderStyle.THIN);
            dataStyleDark.setBorderRight(org.apache.poi.ss.usermodel.BorderStyle.THIN);

            // Write data rows — skip empty rows
            int excelRow = 2;
            for (int row = 0; row < model.getRowCount(); row++) {

                // Skip row if all cells are null
                boolean isEmpty = true;
                for (int col = 0; col < model.getColumnCount(); col++) {
                    if (model.getValueAt(row, col) != null) {
                        isEmpty = false;
                        break;
                    }
                }
                if (isEmpty) {
                    continue;
                }

                org.apache.poi.ss.usermodel.Row dataRow = sheet.createRow(excelRow);
                org.apache.poi.xssf.usermodel.XSSFCellStyle rowStyle = (excelRow % 2 == 0) ? dataStyleLight : dataStyleDark;

                for (int col = 0; col < model.getColumnCount(); col++) {
                    org.apache.poi.ss.usermodel.Cell cell = dataRow.createCell(col);
                    Object value = model.getValueAt(row, col);
                    if (value != null) {
                        cell.setCellValue(value.toString());
                    }
                    cell.setCellStyle(rowStyle);
                }
                excelRow++;
            }

            // Auto-size columns
            for (int col = 0; col < model.getColumnCount(); col++) {
                sheet.autoSizeColumn(col);
            }

            // Save file
            try (java.io.FileOutputStream fos = new java.io.FileOutputStream(fileToSave)) {
                workbook.write(fos);
            }

            JOptionPane.showMessageDialog(this,
                    "Exported successfully to:\n" + fileToSave.getAbsolutePath(),
                    "Export Successful",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Export failed: " + ex.getMessage(),
                    "Export Error",
                    JOptionPane.ERROR_MESSAGE);
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnExportActionPerformed

    private void cmbCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoryActionPerformed
        if (isLoading) {
            return;
        }

        switch (currentView) {
            case "inventory":
                btnInventorySummaryActionPerformed(evt);
                break;
            case "popular":
                btnMostPopularActionPerformed(evt);
                break;
            case "never":
                btnNeverBorrowedActionPerformed(evt);
                break;
            case "recent":
                btnRecentlyAddedActionPerformed(evt);
                break;
        }

    }//GEN-LAST:event_cmbCategoryActionPerformed

    private void btnNeverBorrowedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNeverBorrowedActionPerformed
        // TODO add your handling code here:
        currentView = "never";
        Object selected = cmbCategory.getSelectedItem();
        String category = selected != null ? selected.toString() : "All";

        String sql
                = "SELECT b.book_id, b.title, b.author, c.category_name, "
                + "COUNT(DISTINCT cp.copy_id) AS total_copies, "
                + "COUNT(DISTINCT cp.copy_id) AS available_copies, "
                + "0 AS borrowed_count, "
                + "'Never Borrowed' AS status "
                + "FROM book b "
                + "LEFT JOIN category c ON b.category_id = c.category_id "
                + "LEFT JOIN book_copy cp ON b.book_id = cp.book_id "
                + "LEFT JOIN transaction t ON cp.copy_id = t.copy_id ";

        if (!category.equals("All")) {
            sql += "WHERE c.category_name = ? GROUP BY b.book_id "
                    + "HAVING COUNT(t.transaction_id) = 0";
            loadTableData(sql, category);
        } else {
            sql += "GROUP BY b.book_id "
                    + "HAVING COUNT(t.transaction_id) = 0";
            loadTableData(sql);
        }

    }//GEN-LAST:event_btnNeverBorrowedActionPerformed

    private void btnMostPopularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostPopularActionPerformed
        currentView = "popular";
        Object selected = cmbCategory.getSelectedItem();
        String category = selected != null ? selected.toString() : "All";

        String sql
                = "SELECT b.book_id, b.title, b.author, c.category_name, "
                + "COUNT(DISTINCT cp.copy_id) AS total_copies, "
                + "COUNT(DISTINCT cp.copy_id) - "
                + "COUNT(DISTINCT CASE WHEN t.returned_date IS NULL THEN cp.copy_id END) AS available_copies, "
                + "COUNT(DISTINCT CASE WHEN t.returned_date IS NULL THEN cp.copy_id END) AS borrowed_count, "
                + "'Popular' AS status "
                + "FROM book b "
                + "LEFT JOIN category c ON b.category_id = c.category_id "
                + "LEFT JOIN book_copy cp ON b.book_id = cp.book_id "
                + "LEFT JOIN transaction t ON cp.copy_id = t.copy_id ";

        if (!category.equals("All")) {
            sql += "WHERE c.category_name = ? GROUP BY b.book_id "
                    + "HAVING COUNT(DISTINCT cp.copy_id) > 0 "
                    + "ORDER BY borrowed_count DESC";
            loadTableData(sql, category);
        } else {
            sql += "GROUP BY b.book_id "
                    + "HAVING COUNT(DISTINCT cp.copy_id) > 0 "
                    + "ORDER BY borrowed_count DESC";
            loadTableData(sql);
        }
    }//GEN-LAST:event_btnMostPopularActionPerformed

    private void btnRecentlyAddedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecentlyAddedActionPerformed
        // TODO add your handling code here:
        currentView = "recent";
        Object selected = cmbCategory.getSelectedItem();
        String category = selected != null ? selected.toString() : "All";

        String sql
                = "SELECT b.book_id, b.title, b.author, c.category_name, "
                + "COUNT(DISTINCT cp.copy_id) AS total_copies, "
                + "COUNT(DISTINCT cp.copy_id) AS available_copies, "
                + "0 AS borrowed_count, "
                + "'New' AS status "
                + "FROM book b "
                + "LEFT JOIN category c ON b.category_id = c.category_id "
                + "LEFT JOIN book_copy cp ON b.book_id = cp.book_id ";

        if (!category.equals("All")) {
            sql += "WHERE c.category_name = ? GROUP BY b.book_id "
                    + "ORDER BY b.created_at DESC";
            loadTableData(sql, category);
        } else {
            sql += "GROUP BY b.book_id "
                    + "ORDER BY b.created_at DESC";
            loadTableData(sql);
        }

    }//GEN-LAST:event_btnRecentlyAddedActionPerformed

    private void btnInventorySummaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventorySummaryMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInventorySummaryMouseClicked

    private void btnInventorySummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventorySummaryActionPerformed
        // TODO add your handling code here:
        currentView = "inventory";
        Object selected = cmbCategory.getSelectedItem();
        if (selected == null) {
            return;
        }

        String category = selected.toString();

        String sql
                = "SELECT b.book_id, b.title, b.author, c.category_name, "
                + "COUNT(DISTINCT cp.copy_id) AS total_copies, "
                // ✅ available_copies FIRST (matches loadTableData column order)
                + "COUNT(DISTINCT cp.copy_id) - "
                + "COUNT(DISTINCT CASE WHEN t.returned_date IS NULL THEN cp.copy_id END) AS available_copies, "
                // ✅ borrowed_count SECOND
                + "COUNT(DISTINCT CASE WHEN t.returned_date IS NULL THEN cp.copy_id END) AS borrowed_count, "
                + "CASE WHEN COUNT(DISTINCT cp.copy_id) = "
                + "COUNT(DISTINCT CASE WHEN t.returned_date IS NULL THEN cp.copy_id END) "
                + "THEN 'Out of Stock' ELSE 'Available' END AS status "
                + "FROM book b "
                + "LEFT JOIN category c ON b.category_id = c.category_id "
                + "LEFT JOIN book_copy cp ON b.book_id = cp.book_id "
                + "LEFT JOIN transaction t ON cp.copy_id = t.copy_id ";

        if (!category.equals("All")) {
            sql += "WHERE c.category_name = ? GROUP BY b.book_id";
            loadTableData(sql, category);
        } else {
            sql += "GROUP BY b.book_id";
            loadTableData(sql);
        }


    }//GEN-LAST:event_btnInventorySummaryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BookReports().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnInventorySummary;
    private javax.swing.JButton btnMostPopular;
    private javax.swing.JButton btnNeverBorrowed;
    private javax.swing.JButton btnRecentlyAdded;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblModel;
    private javax.swing.JLabel txtBooks;
    private javax.swing.JLabel txtDashboard;
    private javax.swing.JLabel txtLogout1;
    private javax.swing.JLabel txtMembers;
    private javax.swing.JLabel txtReports;
    private javax.swing.JLabel txtTransactions;
    // End of variables declaration//GEN-END:variables
}
